### ISSUE TITLE
experiment help (same as the email sent to you)

### ISSUE THREAD

**Issue by dczpat** [konsotirop/Invert_Embeddings#1]
Hi, Konstantinos~
I'm an undergraduate at Nanjing University, and am preparing my school project based on your paper DeepWalking Backwards and code.
Please forgive me for reaching out, but I'm facing some trouble when trying to reproduce your experiment.
In your experiments, various graph structures(email, YouTube, BlogCatalog, etc..) are used for comparison to test the learning algorithm, but I don't know where to find the .mat files for these graphs.
So I would thank you very much if you could kindly provide some relevant .mat files(no need to be exactly the same as in the paper) for experiment usage.

**Comment by konsotirop** [comment]
Hi! Could you please send me again an e-mail, using this address "ksotirop at bu dot edu"?
I can forward these .mat files to you.

Thanks,
Konstantinos

**Comment by dczpat** [comment]
Yes, I've already sent an email to that address with my address:
dongchenzhi at smail.nju.edu.cn
maybe it's in you spam bin or something..
or you can just send an email to the above address~
thx again very much!

**Comment by dczpat** [comment]
Alternatively, you can send to my gmail: 
donchangee at gmail.com

**Comment by dczpat** [comment]
Sorry to disturb you again, but I haven't heard from you since last time.
Please let me know if you'd sent me those files.
You can reach me by dongchenzhi@smail.nju.edu.cn~

**Comment by konsotirop** [comment]
Hi, could you please send me again an e-mail at ksotirop at bu.edu<http://bu.edu> and I can forward the relevant .mat files to you.

Thanks,
Konstantinos

On Apr 27, 2022, at 6:47 AM, Patrick ***@***.******@***.***>> wrote:



Hi, Konstantinos~
I'm an undergraduate at Nanjing University, and am preparing my school project based on your paper DeepWalking Backwards and code.
Please forgive me for reaching out, but I'm facing some trouble when trying to reproduce your experiment.
In your experiments, various graph structures(email, YouTube, BlogCatalog, etc..) are used for comparison to test the learning algorithm, but I don't know where to find the .mat files for these graphs.
So I would thank you very much if you could kindly provide some relevant .mat files(no need to be exactly the same as in the paper) for experiment usage.
